_extends: private-global-settings

collaborators:
  # eauge is an owner of this repository
  - username: eauge
    permission: admin
  # nhynes is an owner of this repository
  - username: nhynes
    permission: admin

